### ISSUE TITLE
Build opensource project in Visual studio 2010 using CMake

### ISSUE THREAD

**Issue by AmilaTK** [Dan-Patterson/tools_pro#1]
I receved this 2 error messages while building a project using CMake 3.6.1.
----------------------------------------------------------------------------------------------------------
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SDL2 (missing: SDL2_INCLUDE_DIRS SDL2_LIBS SDL2_DLLS)
Call Stack (most recent call first)
------------------------------------------------------------------------------------------------------------
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  modules/FindSDL2.cmake:57 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)
-------------------------------------------------------------------------------------------------------------
I would be very greatfull if anyone professional can give me some suggetion to reslove this issue

Thank you very much.

**Comment by Dan-Patterson** [comment]
What does this have to do with the toolsets here? Copy the code and use it elsewhere.
