### ISSUE TITLE
How to make the script for Concave Hull (Dan Patterson) to honour all points on the boudnary

### ISSUE THREAD

**Issue by lazarcensus** [Dan-Patterson/tools_pro#2]
The modified script of Dan-Patterson is best bet for converting large point features by grouping them based on attribute values. However, we have different issue to deal with. The ConcaveHull connects the outmost points (using Kn values) and creates tighter polygons. In our case, the point features collected along the census block boundary using QuickCapture Application, the construction should honour all the points (All the points are on the boundary). We use timestamp to short the feature. Normally, the use of timestamp should solve the Point to Line to Poly tool in ArcGIS Pro. But some users collect the points in non-sequential manner and that creates intersecting lines and thus end up with too many or incomplete polygons. 
My request is, can the ConcaveHull Script be modified to honour all the points on the boundary (in our case it is points on census boundary and no points will be inside of it). I am attaching sample data and the results that I have got. Please provide some solution
<img width="960" alt="Concavehull_K3_points to poly" src="https://user-images.githubusercontent.com/55918809/75605607-45f97b80-5b0a-11ea-9f09-7b4b8c1bc982.png">
<img width="960" alt="Non_sequencial_capturing_points_to_line" src="https://user-images.githubusercontent.com/55918809/75605610-485bd580-5b0a-11ea-983b-8d1a294cf973.png">
<img width="960" alt="Points_to_Line_Poly_using Timestamp for shorting" src="https://user-images.githubusercontent.com/55918809/75605613-4a259900-5b0a-11ea-856c-40e292287aa3.png">
[Sample_Points.zip](https://github.com/Dan-Patterson/tools_pro/files/4270159/Sample_Points.zip)

**Comment by lazarcensus** [comment]
The attribute of point feature class has, Census Block Id [HLB_NO], Point type [Point_Type], [DateStamp], [Horz_accuracy], [Direction], Point sequence number [Terminal Point Number]. We can use either DateStamp or Terminal Point Number. If the capturing of points along the Census Block boundary done not in sequence but the input Terminal point number is correct, we will be able to create polygon without any problem. But in cases where the user didn't follow either sequence nor wrongly numbered the points, we need the ConcaveHull should be very helpful, if modified.

**Comment by Dan-Patterson** [comment]
Concave hulls are distance based constructors.   If tightening the constructor brings too many interior points, then that is what it does and is a valid concave hull.  There is no "one" hull since distance between points and point inclusion are the ultimate controllers. Adding a temporal constructor would be require a "must include" option.  It appears a "radial sort" of your collected points will yield the image shown in the last screen grab.  I won't be adding additional components to the existing code to cover cases beyond its initial use.
